### ISSUE TITLE
Random Walk of the Penguins is missing?

### ISSUE THREAD

**Issue by sam477** [drivendataorg/competition-winners#1]
Why Random Walk of the Penguins is missing?

**Comment by pjbull** [comment]
@sam477 Not sure what you're seeing, but on the latest version of master it is there:
https://github.com/drivendataorg/competition-winners

Direct link here if you need it:
https://github.com/drivendataorg/random-walk-of-the-penguins

**Comment by pjbull** [comment]
Nvm, saw that it accidentally wasn't public. It is now, thanks for the issue!
