### ISSUE TITLE
I cannot clone using: git clone --recursive https://github.com/drivendata/competition-winners.git

### ISSUE THREAD

**Issue by kevinwkc** [drivendataorg/competition-winners#3]
I cannot clone using: git clone --recursive https://github.com/drivendata/competition-winners.git
there's nothing in it

Thank You,
Kevin

**Comment by pjbull** [comment]
@kevinwkc Can you share the output from when you run that command?

**Comment by kevinwkc** [comment]
Thanks for checking:
$  git clone --recursive https://github.com/drivendata/competition-winners.git
Cloning into 'competition-winners'...
remote: Counting objects: 107, done.
remote: Total 107 (delta 0), reused 0 (delta 0), pack-reused 107
Receiving objects: 100% (107/107), 18.30 KiB | 936.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
Submodule 'americas-next-top-statistical-model' (https://github.com/drivendataorg/americas-next-top-statistical-model) registered for path 'americas-next-top-statistical-model'
Submodule 'box-plots-for-education' (https://github.com/drivendataorg/box-plots-for-education) registered for path 'box-plots-for-education'
Submodule 'countable-care' (https://github.com/drivendataorg/countable-care) registered for path 'countable-care'
Submodule 'for-fun-competitions' (https://github.com/drivendataorg/for-fun-competitions) registered for path 'for-fun-competitions'
Submodule 'from-fog-nets-to-neural-nets' (https://github.com/drivendata/from-fog-nets-to-neural-nets.git) registered for path 'from-fog-nets-to-neural-nets'
Submodule 'keeping-it-fresh' (https://github.com/drivendataorg/keeping-it-fresh) registered for path 'keeping-it-fresh'
Submodule 'n-plus-one-fish' (https://github.com/drivendataorg/n-plus-one-fish) registered for path 'n-plus-one-fish'
Submodule 'naive-bees-classifier' (https://github.com/drivendataorg/naive-bees-classifier) registered for path 'naive-bees-classifier'
Submodule 'pover-t-tests' (https://github.com/drivendataorg/pover-t-tests) registered for path 'pover-t-tests'
Submodule 'random-walk-of-the-penguins' (https://github.com/drivendataorg/random-walk-of-the-penguins) registered for path 'random-walk-of-the-penguins'
Submodule 'senior-data-science' (https://github.com/drivendata/senior-data-science.git) registered for path 'senior-data-science'
Cloning into 'C:/temp/competition-winners/americas-next-top-statistical-model'...
remote: Counting objects: 30, done.
remote: Total 30 (delta 0), reused 0 (delta 0), pack-reused 30
Cloning into 'C:/temp/competition-winners/box-plots-for-education'...
remote: Counting objects: 82, done.
remote: Total 82 (delta 0), reused 0 (delta 0), pack-reused 82
Cloning into 'C:/temp/competition-winners/countable-care'...
remote: Counting objects: 139, done.
remote: Total 139 (delta 0), reused 0 (delta 0), pack-reused 139
Receiving objects: 100% (139/139), 71.55 KiB | 8.94 MiB/s, done.
Resolving deltas: 100% (73/73), done.
Cloning into 'C:/temp/competition-winners/for-fun-competitions'...
remote: Counting objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Cloning into 'C:/temp/competition-winners/from-fog-nets-to-neural-nets'...
remote: Counting objects: 36, done.
remote: Total 36 (delta 0), reused 0 (delta 0), pack-reused 36
Cloning into 'C:/temp/competition-winners/keeping-it-fresh'...
remote: Counting objects: 39, done.
remote: Total 39 (delta 0), reused 0 (delta 0), pack-reused 39
Cloning into 'C:/temp/competition-winners/n-plus-one-fish'...
remote: Counting objects: 449, done.
remote: Total 449 (delta 0), reused 0 (delta 0), pack-reused 449
Receiving objects: 100% (449/449), 12.95 MiB | 20.16 MiB/s, done.
Resolving deltas: 100% (231/231), done.
Cloning into 'C:/temp/competition-winners/naive-bees-classifier'...
remote: Repository not found.
fatal: repository 'https://github.com/drivendataorg/naive-bees-classifier/' not found
fatal: clone of 'https://github.com/drivendataorg/naive-bees-classifier' into submodule path 'C:/temp/competition-winners/naive-bees-classifier' failed
Failed to clone 'naive-bees-classifier'. Retry scheduled
Cloning into 'C:/temp/competition-winners/pover-t-tests'...
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 115 (delta 29), reused 114 (delta 28), pack-reused 0
Receiving objects: 100% (115/115), 849.66 KiB | 6.74 MiB/s, done.
Resolving deltas: 100% (29/29), done.
Cloning into 'C:/temp/competition-winners/random-walk-of-the-penguins'...
remote: Counting objects: 37, done.
remote: Total 37 (delta 0), reused 0 (delta 0), pack-reused 37
Cloning into 'C:/temp/competition-winners/senior-data-science'...
remote: Counting objects: 182, done.
remote: Total 182 (delta 0), reused 0 (delta 0), pack-reused 182
Receiving objects: 100% (182/182), 31.82 MiB | 22.29 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Cloning into 'C:/temp/competition-winners/naive-bees-classifier'...
remote: Repository not found.
fatal: repository 'https://github.com/drivendataorg/naive-bees-classifier/' not found
fatal: clone of 'https://github.com/drivendataorg/naive-bees-classifier' into submodule path 'C:/temp/competition-winners/naive-bees-classifier' failed
Failed to clone 'naive-bees-classifier' a second time, aborting

**Comment by pjbull** [comment]
It looks like from that output everything except `naive-bees-classifier` should have cloned into `C:/temp/competition-winners`. Is that not the case?

Naïve bees is down for maintenance at the moment, but should be back soon.

**Comment by kevinwkc** [comment]
Thanks, nop, the all the folder only contains .git file, so they are basically empty folder for each submodule.
you can check out file using:git clone --recursive https://github.com/drivendata/competition-winners.git?
Thanks

**Comment by pjbull** [comment]
@kevinwkc Try now, I think it should work.
