### ISSUE TITLE
Error in cloning sub-submodule for pri-matrix-factorization

### ISSUE THREAD

**Issue by r-b-g-b** [drivendataorg/competition-winners#7]
When I clone the repo using `git clone --recursive https://github.com/drivendata/competition-winners.git .` (from [UPDATING.md](https://github.com/drivendataorg/competition-winners/blob/master/UPDATING.md)), I get the error:

> Submodule path 'pri-matrix-factorization': checked out '5b9c6900b1d9ef38a181cfe292716cef3b96d4e1'
> fatal: No url found for submodule path 'pri-matrix-factorization/1st Place/src/cnn_finetune' in .gitmodules
...
> Failed to recurse into submodule path 'pri-matrix-factorization'

`pri-matrix-factorization/1st Place/src/cnn_finetune` appears to be a git submodule itself, but at least in the [GitHub UI](https://github.com/drivendataorg/pri-matrix-factorization/tree/5b9c6900b1d9ef38a181cfe292716cef3b96d4e1/1st%20Place/src), I can't click on it. Maybe the repo it links to disappeared?

**Comment by jayqi** [comment]
Fixed by https://github.com/drivendataorg/pri-matrix-factorization/commit/342399d35c73757def67aa87db8e0d18f4dc6c9d and https://github.com/drivendataorg/pri-matrix-factorization/commit/568b88e56a00de65ff83c8c2afc9fc70773ec201
